kind: Service
apiVersion: v1
metadata:
  name: prometheus-node-exporter
  namespace: kube-system
  labels:
    application: prometheus-node-exporter
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9100"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9100
      protocol: TCP
  selector:
    application: prometheus-node-exporter
