apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-ingress-aws-controller
  namespace: kube-system
  labels:
    application: kube-ingress-aws-controller
    version: v0.6.1
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-ingress-aws-controller
  template:
    metadata:
      labels:
        application: kube-ingress-aws-controller
        version: v0.6.1
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        iam.amazonaws.com/role: "{{ .LocalID }}-app-ingr-ctrl"
    spec:
      serviceAccountName: system
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - name: controller
        image: registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:v0.6.1
        env:
        - name: AWS_REGION
          value: {{ .Region }}
        # Needed in order to find nodes that should be attached to the ALBs.
        # We should switch to the default filter when all nodes has the
        # k8s.io/role/node tag.
        # https://github.com/zalando-incubator/kube-ingress-aws-controller#how-it-works
        - name: CUSTOM_FILTERS
          value: "tag:kubernetes.io/cluster/{{ .ID }}=owned tag:NodePool=worker-default"
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 25Mi
