apiVersion: scheduling.k8s.io/v1alpha1
kind: PriorityClass
metadata:
  name: autoscaling-buffer
value: -1000000
globalDefault: false
description: "This priority class is used by the autoscalling buffer pods."
